### ISSUE TITLE
Neovintageous support?

### ISSUE THREAD

**Issue by webtotma** [acarabott/VintageColor#1]
Does this plugin work with neovintageous?

**Comment by acarabott** [comment]
I haven’t tried it. Can you? :)

It will depend on if they handle modes with the same commands

**Comment by webtotma** [comment]
I tried. This does not work with neovintageous plugin. 

And I really liked the idea of your plugin.This is the little thing that makes the work more comfortable.

**Comment by acarabott** [comment]
I'll try out NeoVintageous and see if I can make it work...

**Comment by webtotma** [comment]
thanks for the plugin anyway )

**Comment by acarabott** [comment]
Have added it, wait until the version on this page changes to 1.3.0 and you should be able to update: https://packagecontrol.io/packages/VintageColor

**Comment by webtotma** [comment]
Thank you very much! I will wait for updating and surely I will try.

**Comment by webtotma** [comment]
Everything works! Thanks.

**Comment by acarabott** [comment]
😄
